# Logging
#CONFIG_LOG=n
#CONFIG_MCUBOOT_LOG_LEVEL_INF=n

# MCUboot Serial Recovery
CONFIG_MCUBOOT_SERIAL=y
CONFIG_BOOT_SERIAL_UART=y

# UART used by serial recovery
CONFIG_UART_CONSOLE=n

# Recovery indication LED
CONFIG_MCUBOOT_INDICATION_LED=y

# GPIO required for button and LED
CONFIG_GPIO=y

# Number of image sectors
CONFIG_BOOT_MAX_IMG_SECTORS=512

# Image signature verification
CONFIG_BOOT_SIGNATURE_TYPE_RSA_LEN=2048
CONFIG_BOOT_VALIDATE_SLOT0=y

CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_NORDIC_QSPI_NOR=n

CONFIG_BOOT_MAX_IMG_SECTORS=512



CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y

#CONFIG_PM_EXTERNAL_FLASH=y
CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y

CONFIG_SPI_NRFX=y
CONFIG_NRFX_SPIM4=y

CONFIG_MULTITHREADING=y