


CONFIG_NRFX_PDM=y
CONFIG_NRFX_CLOCK=y

CONFIG_CLOCK_CONTROL=y
CONFIG_CLOCK_CONTROL_NRF=y

CONFIG_SERIAL=y

CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y

CONFIG_MAIN_STACK_SIZE=8192

CONFIG_AUDIO=y

CONFIG_AUDIO_DMIC=y

CONFIG_SPI=y

CONFIG_LOG=y

CONFIG_GPIO=y

CONFIG_CPP=y
CONFIG_NEWLIB_LIBC=y
CONFIG_LIB_CPLUSPLUS=y

CONFIG_FPU=y
CONFIG_CBPRINTF_FP_SUPPORT=y

# CMSIS DSP
CONFIG_CMSIS_DSP=y
CONFIG_CMSIS_DSP_TRANSFORM=y
CONFIG_CMSIS_DSP_FASTMATH=y

# MCUboot
CONFIG_BOOTLOADER_MCUBOOT=y

# Bluetooth
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="KWS_FOTA"

# MCUmgr
CONFIG_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y



CONFIG_IMG_MANAGER=y
CONFIG_STREAM_FLASH=y

CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_ZCBOR=y


CONFIG_BT_L2CAP_TX_MTU=247

CONFIG_BT_BUF_ACL_RX_SIZE=251
CONFIG_BT_BUF_ACL_TX_SIZE=251

CONFIG_BT_BUF_ACL_RX_COUNT=10
CONFIG_BT_BUF_ACL_TX_COUNT=10

CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251

CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=512

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096
CONFIG_MCUMGR_TRANSPORT_WORKQUEUE_STACK_SIZE=4096

# ==========================================
# SERIAL DFU (MCUmgr over UART)
# ==========================================

#CONFIG_MCUMGR_TRANSPORT_SERIAL=y

CONFIG_UART_INTERRUPT_DRIVEN=y

#CONFIG_MCUMGR_TRANSPORT_SERIAL_UART=y

# Optional but recommended
#CONFIG_MCUMGR_SMP_UART=y
# ----------------------------------------------------
# MCUmgr UART DFU
# ----------------------------------------------------

CONFIG_MCUMGR_TRANSPORT_UART=y

CONFIG_UART_MCUMGR=y

CONFIG_MCUMGR_TRANSPORT_UART_MTU=512

CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=512

CONFIG_BASE64=y

#External memory
#CONFIG_PM_EXTERNAL_FLASH=y
CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y
CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=y

CONFIG_SPI=y
CONFIG_SPI_NOR=y
